name: GitHub Actions - Pull Template Basic
run-name: Running - ${{ github.event_name}}, ${{ github.actor }} is testing out GitHub Actions 🚀 
on: [pull_request]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário do workflow PULL REQUEST WORKFLOW - Basic"