name: GitHub Actions - Configuração de Variável de Repositório
run-name: Running - Secret Repo Config
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "${{ secrets.var_test }}"
