name: GitHub Actions - Workflow dispatch Template Básico - String
run-name: Running - ${{ github.event_name}}, ${{ github.actor }} is testing out GitHub Actions 🚀 
on: 
  workflow_dispatch:
    inputs:
      browser:
        description: Selecione o Browser
        type: string
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário do Workflow dispatch - ${{ inputs.browser }}"