name: GitHub Actions - Workflow dispatch
run-name: Running - ${{ github.event_name}}, ${{ github.actor }} is testing out GitHub Actions 🚀 
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: Selecione a tag 
        type: choice
        options:
          - tag_1
          - tag_2
          - tag_3 
        default: 'tag_1'
        required: true
      browser:
        description: Selecione o Browser
        type: string
      severity:
        description: Funcionalidade Crítica?
        type: boolean
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Tag: ${{ inputs.tags }}"
          echo: "Browser: ${{ inputs.browser }}"
          echo: "Severity: ${{ inputs.severity }}"