name: GitHub Actions - Push Template Basic
run-name: Running - ${{ github.event_name}}, ${{ github.actor }} is testing out GitHub Actions 🚀 
on: 
  push:
    branches:
      - master
      - develop
      - 'feature/*'
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentário do workflow PUSH"
  